### PR TITLE
DJ is back in action

### PR DESCRIPTION
**Pull request by xTrainx**
## About The Pull Request
ports back the DJ station and record burner to hippe from HippieStation/HippieStationdeprecated2020#12830, letting the DJ role play preloaded and custom songs to the station

## Why It's Good For The Game
because music let you lose control

## Changelog
:cl:
add: readded The music station and disk burned to the station
add: added record disk which can be used both to be played on PDA and station wide
add: Disk Jockey PDA has some wild new functions
expansion: Expands content of an existing thing
/:cl:

### CODE REVIEW

**Comment by carlopault** [comment]
This ^ 😱 = 🎶🐒🎶

**Comment by carlopault** [comment]
Code looks functional and he even improved the PDA functionality with the record disks. Pre-coded music needs to be updated to not suck donkey dick.

**Comment by xTrainx** [comment]
@Pyko1 shoot, the linter warning should be gone now

**Comment by carlopault** [comment]
❗❗❗ dj will literally rocket blast hippie to the top of the hub ❗❗❗

**Pull request merged**
